### ISSUE TITLE
Django warning about "makemigrations"

### ISSUE THREAD

**Issue by gabriels1234** [dsoftwareinc/django-tasks-scheduler#119]
**Describe the bug**
my_app-web      |   Your models in app(s): 'scheduler' have changes that are not yet reflected in a migration, and so won't be applied.
my_app-web      |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

**Expected behavior**
I did run makemigrations, but did not apply it, to prevent future messing up with official migrations.
likely the migrations should come from the package, and perhaps this would prevent issues.

**Screenshots**

**Desktop (please complete the following information):**
django-tasks-scheduler==1.3.2

Thanks so much!!!!

**Comment by cunla** [comment]
What is the latest migration you have for `scheduler`?

**Comment by cunla** [comment]
and can you send me the result of `makemigrations`?

**Comment by gabriels1234** [comment]
last migration is 17
this is 18 (makemigrations):
# Generated by Django 5.0.3 on 2024-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_remove_crontask_repeat_crontask_failed_runs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontask',
            name='queue',
            field=models.CharField(choices=[('default', 'default')], help_text='Queue name', max_length=255, verbose_name='queue'),
        ),
        migrations.AlterField(
            model_name='repeatabletask',
            name='queue',
            field=models.CharField(choices=[('default', 'default')], help_text='Queue name', max_length=255, verbose_name='queue'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='queue',
            field=models.CharField(choices=[('default', 'default')], help_text='Queue name', max_length=255, verbose_name='queue'),
        ),
    ]

**Comment by cunla** [comment]
Oh, I see. 

This is happening because you have different `settings.QUEUES` so the new migration "changes" the `BaseTask.queue` field so you can see all the options from `settings.QUEUES` in the dropdown list when creating a task through the admin view.

i.e., it is not a bug - it is a feature :)

I should document it.

**Comment by gabriels1234** [comment]
So how do you make so it does not conflict with further scheduler app migrations you might add in the future. Should I Apply this one migration?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cunla** [comment]
That's a good point! In django 5 they added support for [choices to be a callable](https://docs.djangoproject.com/en/5.0/ref/models/fields/#choices) which would resolve it - but then it would not support django 4...
I will think about it.

**Comment by gabriels1234** [comment]
I saw the change for 1.3.3. 
```
-    QUEUES = [(key, key) for key in settings.QUEUES.keys()]
+    QUEUES = [("default", "default"), ("low", "low"), ("high", "high")]
```
It would break things in many of my projects.

How about this?

```
class BaseTask(models.Model):
    # Other fields remain unchanged

    @property
    def QUEUES(self):
        """Generate queue choices dynamically from settings to prevent migrations."""
        return [(key, key) for key in settings.QUEUES.keys()]

    queue = models.CharField(
        _('queue'), max_length=255, choices=property(lambda self: self.QUEUES),
        help_text=_('Queue name'), )
```
This is supposed to work on v4 as well (haven't tested).

Do you want me to submit a PR and do the proper testing? main goal would be to make it the best possible without breaking v4 compatibility.

**Comment by cunla** [comment]
It should not break things. 
Notice there is another change in `ready()` ([here](https://github.com/dsoftwareinc/django-tasks-scheduler/commit/936c1e0b513f7c16fecab2cb21ccbb6109d6a8d5#diff-b5911c7f49c0ae80cd3a3102ee7bdd2c653d99d65831a258e7c1d938ae0d30afR11-R14))

which updates the value once the project loads.

**Comment by DhavalGojiya** [comment]
Hey @cunla ,
Any update on this?

**Comment by cunla** [comment]
Hi, your solution will still create a migration when running `makemigrations`. Read this: https://github.com/django-commons/django-tasks-scheduler/issues/152

Also, considering v1.3.2 is not maintained anymore (we are in v3.0.0 :) ) - I don't see a need for it. You can make the migration for scheduler.

**Comment by DhavalGojiya** [comment]
Understand,
Thank you @cunla
