### ISSUE TITLE
Task edit view not updating the queues choices

### ISSUE THREAD

**Issue by gabriels1234** [dsoftwareinc/django-tasks-scheduler#132]
**Describe the bug**
Weird behavior where the fix for #119 seemed to have introduced a bug in the edit view of the tasks.

Queues:
<img width="81" alt="image" src="https://github.com/dsoftwareinc/django-tasks-scheduler/assets/96071233/2817c9aa-0600-4b7d-aeba-06eac46ff3ac">

admin/scheduler/crontask/<task_id>/change/:
<img width="228" alt="image" src="https://github.com/dsoftwareinc/django-tasks-scheduler/assets/96071233/4a9ec75e-840d-4235-9912-86b70d3c9ffe">

**Expected behavior**
After the fix for #119, the choices are first fixed, and then updated on page load (I guess). Although Initially I think I saw it working, currently I am not able to change the queue.

**Desktop (please complete the following information):**
 - python version 3.12
 - django==5.0.6 (latest stable)
 - django-tasks-scheduler==1.3.3

Thanks so much!

**Comment by cunla** [comment]
Hi, sorry for the delayed response.. busy days :)
I'll have a look at it this weekend

**Comment by cunla** [comment]
Hi, I am not able to replicate this error.
However, I decided to remove support for older django versions to make this easier to maintain. I release v1.3.4 with up-to-date dependencies.
And will publish v2.0.0 with support for django 5 and above where this is no longer an issue (https://docs.djangoproject.com/en/5.0/ref/models/fields/#choices)

**Comment by gabriels1234** [comment]
Thanks @cunla !
I would love to keep support for django 4.2 especially since it's in LTS until past 2026.
If not, I'd add in the docs that Django 4 projects should pin to 1.3.2 (or try 1.3.3, 1.3.4).
Will keep you posted. Thanks again!
