### ISSUE TITLE
Job becomes unscheduled if you access the admin list page when the job is active

### ISSUE THREAD

**Issue by rstalbow** [dsoftwareinc/django-tasks-scheduler#32]
**Describe the bug**
In this method - https://github.com/dsoftwareinc/django-tasks-scheduler/blob/master/scheduler/models/scheduled_job.py#L83
It checks for jobs in scheduled or queued. If it doesn't find the job it sets the `job_id` to `None` which means after its finished its current execution its doesn't reschedule. 

**To Reproduce**
1. Go to the admin page `admin/scheduler/{repeatablejob/cronjob/scheduledjob}/` and see the green tick against the job to show its scheduled. 
2. Take a look at the queue `admin/scheduler/queue/` and wait for the job to move to active (best to test with a job that takes a few seconds to run). 
3. Go to the admin page `admin/scheduler/{repeatablejob/cronjob/scheduledjob}/` (or refresh page)
4. See the red tick against the job to show its no longer scheduled. 

**Expected behavior**
The job stays scheduled. 

**Implementation idea**
Idea 1:
Add an additional check for the job id in `self.rqueue.started_job_registry.get_job_ids()` 
Idea 2:
Remove the 
```
self.job_id = None
self.save()
```
As I dont see why you would save the database record in this method

**Comment by rstalbow** [comment]
PR against this https://github.com/dsoftwareinc/django-tasks-scheduler/pull/33

**Comment by cunla** [comment]
I agree saving the job in this method isn't the best approach, though I am not sure about your solution..
