### ISSUE TITLE
Job killed mid running not gracefully causes infinite loop

### ISSUE THREAD

**Issue by rstalbow** [dsoftwareinc/django-tasks-scheduler#37]
**Describe the bug**
A worker is killed mid running a job and the shutdown is not graceful. After this happens you get a 500 error accessing `admin/scheduler/queue/` and one of `admin/scheduler/{repeatablejob/cronjob/scheduledjob}/` depending on what type of job was killed when running. The exceptions are 
```
RecursionError
maximum recursion depth exceeded while calling a Python object
```
and 
`Job repeatable_jobs:{jobname}:{jobid}: error while executing failure callback`

This error is due to [this](https://github.com/dsoftwareinc/django-tasks-scheduler/pull/33) change. The `self.rqueue.started_job_registry.get_job_ids()` calls `cleanup` which calls `is_scheduled` thus an infinite loop. 

**To Reproduce**

1. First you need a long running job. For example: 
```
@job()
def test():
    import time
    time.sleep(30)
```
2. Setup the job to run via the admin.
3. When the job is active (by checking the queue `admin/scheduler/queue/`) kill the worker process (for example by `pkill -9 python`)
4. The either: 
    - Bring the worker back up and wait for the maintenance tasks to run 
    - Run the `clean_registries` function from a python django shell

**Expected behavior**
The job gets - `Moved to FailedJobRegistry, due to AbandonedJobError`. This happens to the job if you revert back to version 1.0.2 but then you have this [issue](https://github.com/dsoftwareinc/django-tasks-scheduler/issues/32) again.

**Implementation idea**

1. In the `is_scheduled` function when running `self.rqueue.started_job_registry.get_job_ids()` have an option to not run the cleanup inside of `get_job_ids`. You shouldn't need to run the cleanup from the is_scheduled method. 
2. Revist the fix for [issue](https://github.com/dsoftwareinc/django-tasks-scheduler/issues/32 and instead of adding in `self.rqueue.started_job_registry.get_job_ids()` remove the 
```
self.job_id = None
super(BaseJob, self).save()
```

**Comment by cunla** [comment]
I reverted the change in #32.
Though it is not likely that rq classes call django-tasks-scheduler methods.

**Comment by rstalbow** [comment]
@cunla I don't follow what you are saying regarding tq classes. Now that you have reverted I wouldn't be able to use the latest version as the original bug in [32](https://github.com/dsoftwareinc/django-tasks-scheduler/issues/32) is a major problem for use. 

What do you think to the 2 implementation ideas above? I can make an MR on either tomorrow.

**Comment by cunla** [comment]
Please provide the full stack trace of the error you are getting

**Comment by rstalbow** [comment]
@cunla which error?

**Comment by cunla** [comment]
> This error is due to https://github.com/dsoftwareinc/django-tasks-scheduler/pull/33 change. The `self.rqueue.started_job_registry.get_job_ids()` calls cleanup which calls `is_scheduled` thus an infinite loop.

This does not make sense, can you point me to where `cleanup` calls `is_scheduled`?

**Comment by cunla** [comment]
and you are getting http500, if you activate debug mode, you should get a stacktrace.

**Comment by rstalbow** [comment]
> This does not make sense, can you point me to where cleanup calls is_scheduled?
You can see in the above stacktrace:

```
 File "/home/nobody/.local/lib/python3.11/site-packages/scheduler/models/scheduled_job.py", line 91, in is_scheduled
    active_jobs = self.rqueue.started_job_registry.get_job_ids()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nobody/.local/lib/python3.11/site-packages/rq/registry.py", line 152, in get_job_ids
    self.cleanup()
  File "/home/nobody/.local/lib/python3.11/site-packages/rq/registry.py", line 238, in cleanup
    job.execute_failure_callback(
  File "/home/nobody/.local/lib/python3.11/site-packages/rq/job.py", line 1429, in execute_failure_callback
    self.failure_callback(self, self.connection, *exc_info)
  File "/home/nobody/.local/lib/python3.11/site-packages/scheduler/models/scheduled_job.py", line 34, in callback_save_job
    scheduled_job.unschedule()
  File "/home/nobody/.local/lib/python3.11/site-packages/scheduler/models/scheduled_job.py", line 210, in unschedule
    if self.is_scheduled():
```

**Comment by cunla** [comment]
fixed on 1.2.1

**Comment by rstalbow** [comment]
This change might have fixed one issue but its caused a bigger issue. 
We have our scheduler interval configured like this:
```
SCHEDULER_CONFIG = {
    "SCHEDULER_INTERVAL": 1  # In seconds
}
```

The jobs now run with an interval of 1 second regardless of whether they are enabled or not and ignores the interval defined in the job. 

![Screenshot from 2023-10-09 18-04-29](https://github.com/dsoftwareinc/django-tasks-scheduler/assets/1573276/3669ccca-a12d-4fcd-b150-a788eb19bc0e)

Screenshot above shows the job is scheduled to run every hour.

![Screenshot from 2023-10-09 18-04-53](https://github.com/dsoftwareinc/django-tasks-scheduler/assets/1573276/94c18a12-e480-4edd-95aa-0211c63eeeed)

Screenshot above shows the job is running every second

I believe the issues is in the `callback_save_job` where you have added `force_schedule`. Inside of `force_schedule` its runs `self._schedule_time()`. This is the datetime of the very first time it was set to run. It then does an `enqueue_at` at and as the  `schedule_time` is now in the past it runs it. `callback_save_job` is run everytime the job is run.

**Comment by cunla** [comment]
you can create a new one. if you can write a test to replicate this it would help fix it.
