### ISSUE TITLE
Adding Cron Jobs via Code

### ISSUE THREAD

**Issue by mikenester** [dsoftwareinc/django-tasks-scheduler#40]
**Is your feature request related to a problem? Please describe.**
I'd like to control my cron jobs via Code.

**Describe the solution you'd like**
I'd be great to be able to add Cron Jobs via code, similar to [enqueing jobs](https://django-tasks-scheduler.readthedocs.io/en/latest/usage/#enqueue-jobs-from-code)

**Describe alternatives you've considered**
n/a

**Additional context**
If this already exists, I'd like the request to be to update the Doc with an example.

**Comment by cunla** [comment]
You can create cron-jobs from code, but be careful, the cron-jobs, like all jobs, are saved in the database, so if the code for creating a cron-job will create a job every time it runs. You should create a check to ensure there isn't one already in the database:

```python
 CronJob.objects.create(name='Scheduled Job 1',
                        job_id=None,
                        queue='default',
                        callable='scheduler.tests.jobs.test_job',
                        enabled=True,
                        timeout=None,
                        cron_string="0 0 * * *",
                        repeat=None, )
```
