### ISSUE TITLE
Jobs get scheduled for immediate execution after previous execution has finished

### ISSUE THREAD

**Issue by rstalbow** [dsoftwareinc/django-tasks-scheduler#41]
The change in [this](https://github.com/dsoftwareinc/django-tasks-scheduler/issues/37) caused a bigger issue.
We have our scheduler interval configured like this:

SCHEDULER_CONFIG = {
    "SCHEDULER_INTERVAL": 1  # In seconds
}
The jobs now run with an interval of 1 second regardless of whether they are enabled or not and ignores the interval defined in the job.

![Screenshot from 2023-10-09 18-04-29](https://github.com/dsoftwareinc/django-tasks-scheduler/assets/1573276/f7c67519-c548-4bd8-910b-87b730c59c6f)

Screenshot above shows the job is scheduled to run every hour.

![Screenshot from 2023-10-09 18-04-53](https://github.com/dsoftwareinc/django-tasks-scheduler/assets/1573276/a300192f-a4b4-4aeb-8e42-0766192b6b12)

Screenshot above shows the job is running every second

I believe the issues is in the callback_save_job where you have added force_schedule. Inside of force_schedule its runs self._schedule_time(). This is the datetime of the very first time it was set to run. It then does an enqueue_at at and as the schedule_time is now in the past it runs it. callback_save_job is run everytime the job is run.

I can try and write a test to replicate this tomorrow

**Comment by cunla** [comment]
I released a new version that I believe should resolve it.
Please let me know.

**Comment by rstalbow** [comment]
Hi @cunla this issue is now fixed, thanks but its created another issue (issue wasnt present in `django-tasks-scheduler==1.2.0`). Want me to create a new issue for it or detail here?
