### ISSUE TITLE
Python 3.12 Admin  (template)  EnumType: `EnumType.__call__() missing 1 required positional argument: 'value'`

### ISSUE THREAD

**Issue by gabriels1234** [dsoftwareinc/django-tasks-scheduler#49]
Hi!

I reverted back to 3.11, Posting this for visibility.

I'm Glad to be back!

**Comment by cunla** [comment]
Welcome back! Can you provide a full stacktrace?

**Comment by cunla** [comment]
Based on my analysis, the issue comes from `rq` - the `Result` class has a subclass `Type` which django+py3.12 tries to render as a field.
Changing `Result.Type` to `Result.ResultType` fixes it.

At some point I am going to take migrating away from `rq` more seriously - just need more time.

**Comment by cunla** [comment]
Thanks! merged
