### ISSUE TITLE
cron job infnite call

### ISSUE THREAD

**Issue by momenkittaneh** [dsoftwareinc/django-tasks-scheduler#56]
when I add a cron task with Cron string 2 */1 * * *
it runs infinitely when the job is finished it executes infinitely without stop
and even in repeated tasks it still executes infinitely 

this is my settings

SCHEDULER_CONFIG = {
    'EXECUTIONS_IN_PAGE': 20,
    'DEFAULT_RESULT_TTL': 500,
    'DEFAULT_TIMEOUT': 300,  # 5 minutes
    'SCHEDULER_INTERVAL': 10,  # 10 seconds
}

SCHEDULER_QUEUES = {
    'default': {
        'URL': 'redis://localhost:6379/0',
        'DEFAULT_TIMEOUT': 360,
    },
}

can you help me with this problem?
and thank you

**Comment by cunla** [comment]
Do you mind sharing your setup?
What django-tasks-scheduler version? rq version? django version? python version? 

> it runs infinitely when the job is finished it executes infinitely without stop
 
Please elaborate what is "it"? the job finishes, so what executes infinitely?

**Comment by cunla** [comment]
Closing due to lack of response

**Comment by momenkittaneh** [comment]
@cunla
it run when the task is finished it qoued again and rerun instanly not on the time i put it in scedule

**Comment by cunla** [comment]
Please provide more details, see comments above.

**Comment by momenkittaneh** [comment]
@cunla 
for example, when I make a scheduled job work every hour eg xx:30 it adds to queues and starts work and finishes either failed or successes the next scheduled queue with the same job start instantly not in the next hour with an infinite cycle, and the server stop response
