### ISSUE TITLE
v1.2.4: Failed CRON jobs aren't requeued

### ISSUE THREAD

**Issue by geonyoro** [dsoftwareinc/django-tasks-scheduler#75]
**Describe the bug**
When a job scheduled as a CRON Job fails, by raising an error, it isn't re queued. Indications of it not being re-queued are on the django-admin UI and include a - appearing as the next scheduled time, and no entry for next scheduled jobs when clicking into each cron job. 

**To Reproduce**
1. Create a task in any app module that will raise an error. Set up a cron string of every minute.
2. Create a job that calls that task.
3. Run the worker and the scheduler.
4. S

**Expected behavior**
The job ideally should execute, and fail, and the next scheduled job should not be prevented from being created and/OR running. In current version, the job fails, and none fails.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint/Ubuntu
 - python.311
 - django 4.1

**Comment by cunla** [comment]
What django-tasks-scheduler version are you using?

**Comment by cunla** [comment]
I wrote a test for the scenario you mentioned (see commit).
Seems like it is rescheduled?

**Comment by cunla** [comment]
Closing
