### ISSUE TITLE
django-tasks-scheduler should be database agnostic

### ISSUE THREAD

**Issue by mbi** [dsoftwareinc/django-tasks-scheduler#77]
**Describe the bug**
pyproject.toml lists `psycopg2 = "^2.9.9"` as a dependency.

Is this really the case? Does the app not work with other database backends supported by Django?

Also we tend to prefer installing `psycopg2-binary` as it has fewer system dependencies. As it is we end up installing both psycopg2 and psycopg2-binary :shrug: 

```
...
psycopg2==2.9.9
    # via django-tasks-scheduler
psycopg2-binary==2.9.9
    # via -r requirements.in
...
```

**To Reproduce**
1. install django-tasks-scheduler via any tool that handles dependencies

**Expected behavior**
Ideally django-tasks-scheduler should be database agnostic

**Comment by cunla** [comment]
You are right.
Can you publish a PR for this?
