### ISSUE TITLE
Auto-reload workers page issue with template

### ISSUE THREAD

**Issue by gabriels1234** [dsoftwareinc/django-tasks-scheduler#83]
**Describe the bug**
when running locally, and making changes to the code I sometimes encounter an error screen when accessing the Workers Page:

<img width="659" alt="image" src="https://github.com/dsoftwareinc/django-tasks-scheduler/assets/96071233/02dd2f1f-ba7a-432c-b0c6-0e94edd442d3">

The part of the code that might need some error handling:

<img width="655" alt="image" src="https://github.com/dsoftwareinc/django-tasks-scheduler/assets/96071233/ef6efc29-e955-44a2-8d6b-d278399a534e">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS.
 - python version: 3.11
 - django version: 4.2.9
 - requirements.txt?....

Thanks!!!

**Comment by cunla** [comment]
what is the error? stack trace?
